#pragma once

enum	INPUT_TYPE
{
	//VOICE SPECIFIC
	XBOX, //say this to initialize shit
	VOICE_ACTIVATE, VOICE_DEACTIVATE,
	
	//DATA STUFF
	UNLOCK_ALL_DATA, LOCK_ALL_DATA,

	//GENERAL COMMANDS
	UP, DOWN, LEFT, RIGHT, SELECT, BACK, NEXT, PREVIOUS, PLAY,
	
	//SPECIFIC PLAY ON GENERAL COMMANDS
	VOICE_UP, VOICE_DOWN, VOICE_LEFT, VOICE_RIGHT,

	//EVERGREEN
	HANDBOOK, BEACON,
	
	//START VIEW
	START_EPISODE, HOST_A_PARTY, PREFERENCES,

	//HOST
	INVITE, UNINVITE,

	//PREFS VIEW
	SUBTITLES_ON, SUBTITLES_OFF, CLOSED_CAPTIONS_ON, CLOSED_CAPTIONS_OFF,
	NOTIFICATIONS_ON, NOTIFICATIONS_OFF, SOCIAL_NOTIFICATIONS_ON, SOCIAL_NOTIFICATIONS_OFF,
	VOICE_COMMAND_ON, VOICE_COMMAND_OFF, AUTOSHARE_ON, AUTOSHARE_OFF,

	//LONGFORM
	DATA, LOCATION, ONI, PAUSE,

	//LOCATION
	ORBITAL, AERIAL, LOCAL,

	//DATA
	OVERVIEW, WAYPOINT,
	

	//XBOX CONTROLLER COMMANDS
	PRESSED_A, PRESSED_B, PRESSED_X, PRESSED_Y,
	DPAD_UP, DPAD_DOWN, DPAD_LEFT, DPAD_RIGHT,
	RIGHT_SHOULDER, LEFT_SHOULDER, START,
	LEFT_STICK_LEFT, LEFT_STICK_RIGHT, LEFT_STICK_UP, LEFT_STICK_DOWN,
};
